import type { AccidentReport, DashboardStats, RegionStat, TrendPoint } from './types'

export const mockAccidents: AccidentReport[] = [
  {
    id: 'ACC-2024-001',
    createdAt: '2024-04-20T08:32:00Z',
    updatedAt: '2024-04-20T10:15:00Z',
    status: 'under_review',
    severity: 'critical',
    dateTime: '2024-04-20T08:15:00Z',
    location: {
      lat: 5.6037,
      lng: -0.187,
      address: 'N1 Highway, Accra',
      road: 'Tema Motorway',
      landmark: 'Near Accra Mall',
    },
    weather: 'clear',
    vehicle: {
      model: 'Toyota Corolla',
      chassisNumber: 'JTDBE32K503091234',
      plateNumber: 'GR-2456-21',
      vehicleType: 'sedan',
      color: 'Silver',
    },
    people: { driverName: 'Kwame Mensah', passengerCount: 2, injuryStatus: 'severe' },
    accidentType: 'rear_end',
    description: 'Vehicle rear-ended by speeding truck at the highway junction. Driver sustained injuries. Two passengers with minor cuts.',
    mediaUrls: [],
    officerNotes: 'Scene cleared. Tow truck dispatched.',
    region: 'Greater Accra',
  },
  {
    id: 'ACC-2024-002',
    createdAt: '2024-04-19T14:20:00Z',
    updatedAt: '2024-04-19T16:00:00Z',
    status: 'resolved',
    severity: 'moderate',
    dateTime: '2024-04-19T14:05:00Z',
    location: {
      lat: 6.6885,
      lng: -1.6244,
      address: 'Kumasi Inner Ring Road',
      road: 'Ring Road East',
      landmark: 'Kejetia Market',
    },
    weather: 'rain',
    vehicle: {
      model: 'Hyundai Tucson',
      chassisNumber: 'KMHJ341HBAU123456',
      plateNumber: 'AE-5123-22',
      vehicleType: 'suv',
      color: 'White',
    },
    people: { driverName: 'Abena Asante', passengerCount: 1, injuryStatus: 'minor' },
    accidentType: 'side_swipe',
    description: 'Side swipe collision at the roundabout during heavy rain. Minor body damage to both vehicles.',
    mediaUrls: [],
    region: 'Ashanti',
  },
  {
    id: 'ACC-2024-003',
    createdAt: '2024-04-19T09:45:00Z',
    updatedAt: '2024-04-19T11:30:00Z',
    status: 'pending',
    severity: 'minor',
    dateTime: '2024-04-19T09:30:00Z',
    location: {
      lat: 5.1037,
      lng: -1.2827,
      address: 'Cape Coast - Takoradi Road',
      road: 'N8 Highway',
      landmark: 'University of Cape Coast',
    },
    weather: 'fog',
    vehicle: {
      model: 'Kia Sportage',
      chassisNumber: 'KNDJP3A59J7891234',
      plateNumber: 'CE-0987-20',
      vehicleType: 'suv',
      color: 'Black',
    },
    people: { driverName: 'Kofi Boateng', passengerCount: 0, injuryStatus: 'none' },
    accidentType: 'single_vehicle',
    description: 'Vehicle skidded off road due to fog. No injuries. Minor damage to front bumper.',
    mediaUrls: [],
    region: 'Central',
  },
  {
    id: 'ACC-2024-004',
    createdAt: '2024-04-18T17:55:00Z',
    updatedAt: '2024-04-19T09:00:00Z',
    status: 'closed',
    severity: 'resolved',
    dateTime: '2024-04-18T17:40:00Z',
    location: {
      lat: 5.5607,
      lng: -0.2057,
      address: 'Liberation Road, Accra',
      road: 'Liberation Road',
      landmark: 'Paloma Hotel',
    },
    weather: 'clear',
    vehicle: {
      model: 'Ford Ranger',
      chassisNumber: '1FTER4FH3JLA56789',
      plateNumber: 'GW-3312-19',
      vehicleType: 'truck',
      color: 'Red',
    },
    people: { driverName: 'Ama Owusu', passengerCount: 3, injuryStatus: 'minor' },
    accidentType: 'pedestrian',
    description: 'Vehicle grazed pedestrian at crossing. Pedestrian sustained minor leg injury. Driver stopped and assisted.',
    mediaUrls: [],
    officerNotes: 'Report filed. Pedestrian treated and discharged.',
    region: 'Greater Accra',
  },
  {
    id: 'ACC-2024-005',
    createdAt: '2024-04-18T11:20:00Z',
    updatedAt: '2024-04-18T13:45:00Z',
    status: 'under_review',
    severity: 'critical',
    dateTime: '2024-04-18T11:00:00Z',
    location: {
      lat: 10.0667,
      lng: -2.5,
      address: 'Tamale Bypass Road',
      road: 'N10 Highway',
      landmark: 'Tamale Stadium',
    },
    weather: 'harmattan',
    vehicle: {
      model: 'Mitsubishi Pajero',
      chassisNumber: 'JA4AZ3A3XHZ123456',
      plateNumber: 'NE-0671-23',
      vehicleType: 'suv',
      color: 'Blue',
    },
    people: { driverName: 'Ibrahim Abdallah', passengerCount: 4, injuryStatus: 'severe' },
    accidentType: 'rollover',
    description: 'Vehicle rolled over on sharp curve during harmattan dust. Driver and passengers critically injured. Emergency services called.',
    mediaUrls: [],
    region: 'Northern',
  },
  {
    id: 'ACC-2024-006',
    createdAt: '2024-04-17T16:30:00Z',
    updatedAt: '2024-04-17T18:00:00Z',
    status: 'resolved',
    severity: 'moderate',
    dateTime: '2024-04-17T16:15:00Z',
    location: {
      lat: 6.9212,
      lng: -1.6077,
      address: 'Sunyani Bypass',
      road: 'R65 Road',
      landmark: 'Sunyani Market',
    },
    weather: 'clear',
    vehicle: {
      model: 'Honda Civic',
      chassisNumber: '2HGFC2F64JH234567',
      plateNumber: 'BN-1123-21',
      vehicleType: 'sedan',
      color: 'Gray',
    },
    people: { driverName: 'Yaa Frimpong', passengerCount: 1, injuryStatus: 'minor' },
    accidentType: 'head_on_collision',
    description: 'Head-on collision with oncoming vehicle while overtaking. Both drivers sustained minor injuries.',
    mediaUrls: [],
    region: 'Bono',
  },
]

export const dashboardStats: DashboardStats = {
  today: 4,
  week: 27,
  month: 112,
  critical: 18,
  moderate: 43,
  minor: 31,
  resolved: 20,
}

export const regionStats: RegionStat[] = [
  { region: 'Greater Accra', count: 42, critical: 8, moderate: 18, minor: 16 },
  { region: 'Ashanti', count: 31, critical: 5, moderate: 14, minor: 12 },
  { region: 'Western', count: 14, critical: 2, moderate: 7, minor: 5 },
  { region: 'Central', count: 9, critical: 1, moderate: 4, minor: 4 },
  { region: 'Northern', count: 8, critical: 2, moderate: 3, minor: 3 },
  { region: 'Volta', count: 5, critical: 0, moderate: 2, minor: 3 },
  { region: 'Bono', count: 3, critical: 0, moderate: 2, minor: 1 },
]

export const trendData: TrendPoint[] = [
  { date: 'Apr 14', total: 8, critical: 1, moderate: 4, minor: 3 },
  { date: 'Apr 15', total: 12, critical: 3, moderate: 5, minor: 4 },
  { date: 'Apr 16', total: 6, critical: 1, moderate: 2, minor: 3 },
  { date: 'Apr 17', total: 15, critical: 4, moderate: 6, minor: 5 },
  { date: 'Apr 18', total: 9, critical: 2, moderate: 4, minor: 3 },
  { date: 'Apr 19', total: 11, critical: 2, moderate: 5, minor: 4 },
  { date: 'Apr 20', total: 4, critical: 2, moderate: 1, minor: 1 },
]

export const vehicleTypeData = [
  { name: 'Sedan', value: 38, color: '#2563EB' },
  { name: 'SUV', value: 29, color: '#0D9488' },
  { name: 'Truck', value: 18, color: '#F59E0B' },
  { name: 'Motorcycle', value: 11, color: '#DC2626' },
  { name: 'Bus', value: 4, color: '#8B5CF6' },
]

export const hourlyData = [
  { hour: '00', count: 1 },
  { hour: '02', count: 0 },
  { hour: '04', count: 1 },
  { hour: '06', count: 4 },
  { hour: '08', count: 9 },
  { hour: '10', count: 7 },
  { hour: '12', count: 6 },
  { hour: '14', count: 8 },
  { hour: '16', count: 12 },
  { hour: '18', count: 15 },
  { hour: '20', count: 10 },
  { hour: '22', count: 5 },
]
